// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeTdYtbhCFk3Q9aKvCqJ5X2_oVXKS_c64',
    appId: '1:1083511737820:web:3f6b7d4cb458e0e2b65319',
    messagingSenderId: '1083511737820',
    projectId: 'mymoney-dev-e5f69',
    authDomain: 'mymoney-dev-e5f69.firebaseapp.com',
    storageBucket: 'mymoney-dev-e5f69.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOtuYv7PmVEqbCMpbRLAg7gpRKjQrEOEU',
    appId: '1:1083511737820:android:40456fc74a80b853b65319',
    messagingSenderId: '1083511737820',
    projectId: 'mymoney-dev-e5f69',
    storageBucket: 'mymoney-dev-e5f69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy62S8zaIBVdOHsIrnfcTb7s_JQrcLM3I',
    appId: '1:1083511737820:ios:306fe521e25668d9b65319',
    messagingSenderId: '1083511737820',
    projectId: 'mymoney-dev-e5f69',
    storageBucket: 'mymoney-dev-e5f69.appspot.com',
    iosClientId: '1083511737820-3p3ff2ni5kobbiid8iuqnd06rva5q432.apps.googleusercontent.com',
    iosBundleId: 'com.ikwuh.mymoney',
  );
}
